const pages = {
    page1: {
        id: "1",
        title: "Chardonnay",
        desc: "OEIL DE FAUCON GOLD CHARDONNAY IS A DELUXE SPARKLING WINE WITH 22K GOLD - A WINNING COMBINATION OF METHODE CLASSIQUE AND THE PERFECT RECIPE. <br/><br/> THIS LUXURY CHARDONNAY EDITION IS ENRICHED WITH  EXTRAORDINARY AROMAS TO CREATE A PERFECT BALANCE OF POWER AND FINESSE. <br/><br/> THE UNFORGETTABLE TASTE OF OEIL DE FAUCON 22K GOLD CHARDONNAY MAKES ANY SPECIAL OCCASION SUCH AS  A ROMANTIC DINNER, EXCLUSIVE PARTIES OR EVENTS,  WEDDING CELEBRATIONS, BUSINESS METTINGS OR GIFTS EVEN MORE SPECIAL.",
        contains: "Blanc de Blancs Extra Dry",
        bg: "./img/bg_01.jpg",
        img_center: "",
        img_upper: "",
        img_lower:"",
    },
    page2: {
        id: "2",
        title: "Rosé",
        desc: "OEIL DE FAUCON ROSE WITH 22K GOLD IS A PRECIOUS SPARKLING WINE READY TO MAKE YOUR FINEST MOMENT UNFORGETTABLE. THIS LUXURY AND PRESTIGE BRAND IS THE PERFECT BALANCE OF POWER AND FINESSE, AN OVERWHELMING RANGE OF VARIETIES LIKE NO OTHER. <br/>A QUALITY THAT MAKES YOU BEG FOR MORE.<br/><br/> DON'T MISS THE OPPORTUNITY TO TREAT YOUR TASTE BUDS TO OEIL DE FAUCON ROSE SPARKLING WINE WITH <br/> 22 K GOLD ADDING TO ITS ALREADY EXCLUSIVE QUALITY.<br/><br/> CELEBRATED FOR ITS EXCELLENCE, OEIL DE FAUCON ROSE IS THE PERFECT PRESENT, ADDING MAGIC TO ANY OCCASION.",
        contains: "Pinot Noir Extra Dry",
        bg: "./img/bg_02.jpg",
        img_center: "",
        img_upper: "",
        img_lower:"",
    },
    page3: {
        id: "3",
        title: "Luxury Life",
        desc: "",
        contains: "Chardonnay Extra Dry",
        bg: "",
        img_center: "./img/img_center_03.jpg",
        img_upper: "",
        img_lower:"",
    },
    page4: {
        id: "4",
        title: "Prestige Brand",
        desc: "",
        contains: "Chardonnay and Pinot Noir Extra Dry",
        bg: "",
        img_center: "",
        img_upper: "./img/img_upper_04.jpg",
        img_lower:"./img/img_lower_04.jpg",
    },
    page5: {
        id: "5",
        title: "Tradition",
        desc: "",
        contains: "Chardonnay and Pinot Noir Extra Dry",
        bg: "",
        img_center: "./img/img_center_05.jpg",
        img_upper: "",
        img_lower:"",
    },
    page6: {
        id: "6",
        title: "Rich Taste",
        desc: "",
        contains: "Chardonnay and Pinot Noir Extra Dry",
        bg: "",
        img_center: "",
        img_upper: "./img/img_upper_06.jpg",
        img_lower:"./img/img_lower_06.jpg",
    },
    page7: {
        id: "7",
        title: "More Coming Soon",
        desc: "",
        contains: "Chardonnay and Pinot Noir Extra Dry",
        bg: "",
        img_center: "",
        img_upper: "",
        img_lower:"",
    },
}

export {pages}